model:
  texture_network:
    _target_: lib.model.network.TextureNetwork
    d_in: 3
    d_out: 3
    width: 256 #128
    depth: 6 #4
    weight_norm: true
    multires: 6
    pose_cond_dim: 69
    pose_cond_layer: []
    pose_embed_dim: -1
    shape_cond_dim: 10
    shape_cond_layer: []
    shape_embed_dim: -1
    latent_cond_dim: ${model.dim_texture}
    latent_cond_layer: [0, 4]
    skip_in: []
    latent_embed_dim: -1
    feat_cond_dim: 256
    feat_cond_layer: [0]